/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nanfeng_fmoddemo_EffectUtil */

#ifndef _Included_com_nanfeng_fmoddemo_EffectUtil
#define _Included_com_nanfeng_fmoddemo_EffectUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nanfeng_fmoddemo_EffectUtil
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_nanfeng_fmoddemo_EffectUtil_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
